export { default as SmallArrowDown } from "./fi-sr-angle-small-down.svg";
export { default as FiSrPlane } from "./fi-sr-plane.svg";
export { default as FlightCardDivider } from "./flight-card-divider.svg";
export { default as FiBrPlane } from "./fi-br-plane.svg";
export { default as FiBrBookmark } from "./fi-br-bookmark.svg";
export { default as FiBrUser } from "./fi-br-user.svg";
export { default as FiBrSettings } from "./fi-br-setting.svg";
export { default as MagnifyIcon } from "./magnify_icon.svg";
export {default as TimeForwardIcon} from "./fi-br-time-forward.svg";
export {default as TwoWayArrowIcon} from "./two-way-arrow.svg";